### ISSUE TITLE
Div IDs system on class-tree view

### ISSUE THREAD

**Issue by dsimansk** [atlasmap/atlasmap-ui#31]
Would it be possible to introduce some kind of ID system to tree view of `Sources` to `Target` columns?

It would be very helpful and streamlined implementation of our e2e tests. If for example field div would hold id based on a `label`, but anything that eases up selecting the exact element based on a field name would definitely help.

@jludvice feel free to chime in as I probably didn't provide all the necessary details. 

Cc @gashcrumb

**Comment by jbakermd** [comment]
@dsimansk or @jludvice can you elaborate on the ID scheme you're thinking of, and where in the UI you need these ids? 

Are you asking for a unique auto-generated ID per field listed in the source/target cards?

**Comment by jbakermd** [comment]
I *think* I understand what you're asking for, here's what I've done. 

In the example attached screenshot the user has selected the highlighted "addressline1" field. 

![screenshot 2017-07-18 12 23 48](https://user-images.githubusercontent.com/26657480/28330932-fcbb85f4-6bb4-11e7-9a53-36d1460a1d16.png)

The path to that field is SourceOrder -> address -> addressline1.

I've attached a screenshot showing an example DOM. 

![screenshot 2017-07-18 12 29 07](https://user-images.githubusercontent.com/26657480/28330941-0339e6a0-6bb5-11e7-9be4-ecb734d1aa63.png)

The important bits of that DOM are the following:

```
<div class="docIdentifier" id="SourceOrder">
  <div class="DocumentFieldDetailComponent" id="address">
    <div class="DocumentFieldDetailComponent" id="addressLine1"></div>
  </div>
</div>
```

Looking this field up in the DOM would require the following:

a) find the div with class "docIdentifier" that has an id of "SourceOrder"
b) within the "SourceOrder" div, find the child div with class "DocumentFieldDetailComponent" with id "address"
c) within the "address" div, find the child div with class "DocumentFieldDetailComponent" with id "addressLine1"

Note that you can't just look for the div with id "addresLine1", because there could be multiple fields across multiple source documents with that id.

**Comment by dsimansk** [comment]
This looks great, thanks @jbakermd. I'll talk to @jludvice once he's back from vacation, if he needs any more adjustments. But I feel like your impl is exactly what was required 👍 .

**Comment by jbakermd** [comment]
@dsimansk great. closing for now. feel free to reopen or open another ticket if further div ids are needed in other places.
